ruby '3.0.2'

source "https://rubygems.org"

gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sqlite3', '~> 1.3', '>= 1.3.11'
gem 'rake'
gem 'simplecov', require: false, group: :test
gem 'bcrypt'
gem 'rubocop'
gem 'rackup'
gem 'puma'

group :test, :development do
    gem 'rspec'
    gem 'rack-test'
end
