ruby '3.3.2'

source "https://rubygems.org"

gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sqlite3', '~> 1.3', '>= 1.3.11'
gem 'rake'
gem 'rufus-scheduler'
gem 'tzinfo-data'

group :test, :development do
    gem 'rspec'
    gem 'rack-test'
end