# frozen_string_literal: true

ruby '3.3.4'

source 'https://rubygems.org'

gem 'activerecord'
gem 'bcrypt'
gem 'puma'
gem 'rackup'
gem 'rake'
gem 'rubocop'
gem 'simplecov', require: false, group: :test
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sqlite3', '~> 1.3', '>= 1.3.11'

group :test, :development do
  gem 'rack-test'
  gem 'rspec'
end
